sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: "1115"
  redis:
    host: localhost
    port: 6379
    database: 1
  wechat:
    appid: wxb393a846201823e2
    secret: 1ccea017cd659ed9efb5f838bb44fe44